name: Deploy .NET API to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore OfficeBuilderAPI.sln

      - name: Build API
        run: dotnet build OfficeBuilderAPI.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test OfficeBuilderAPI.Tests/OfficeBuilderAPI.Tests.csproj --no-build --logger trx

      - name: Publish API
        run: dotnet publish OfficeBuilderAPI/OfficeBuilderAPI.csproj --configuration Release --output ./publish

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: officebuilder-api 
          publish-profile: ${{ secrets_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
